### ISSUE TITLE
Not working on XCode 14

### ISSUE THREAD

**Issue by meshwara** [sugarmo/XCFormat#9]
XCFormat not working on Xcode 14.x. XCFormat not showing in Extensions list on System Preferences

**Comment by pbertaco** [comment]
Objctive-C formating still works on XCode 14.2.

Swift formating gives the error "Error message is too long, please check the log in Console" and the Console is empty.

**Comment by pbertaco** [comment]
I deleted all Xcode temporary files using a tool called "Cleaner for Xcode" and then after tring to build again I find out tha there was an INVALID CHARACTER on my code... 🥲 
Formating now works fine.

**Comment by meshwara** [comment]
After reinstall the newest XCode 14.x, Formating now forks just fine !!
